// Default reminder copy, keyed by offset (days relative to due_date) and
// language. This is the fallback used whenever a user hasn't saved a
// custom template for a given language/stage — see email_templates and
// draft-templates.ts for the AI-assisted, per-user version.
//
// One hard rule that never changes even for custom templates: the
// amount, date, invoice number, and bank details are always inserted as
// plain variables, never generated by a model. That's what makes it safe
// to automate.

export type BankDetails = {
  bank_name?: string
  branch_name?: string
  account_type?: string
  account_number?: string
  account_holder?: string
}

type TemplateInput = {
  clientName: string
  invoiceNumber: string
  amount: number
  currency: string
  dueDate: string
  businessName: string
  bankDetails?: BankDetails | null
}

type Template = { subject: string; body: string }

export function formatAmount(amount: number, currency: string) {
  return `${currency} ${amount.toLocaleString()}`
}

export function bankSection(bank: BankDetails | null | undefined, lang: 'ja' | 'en') {
  if (!bank || !bank.bank_name) return ''
  if (lang === 'ja') {
    return `\n\n【お振込先】\n銀行名: ${bank.bank_name}\n支店名: ${bank.branch_name ?? ''}\n口座種別: ${bank.account_type ?? ''}\n口座番号: ${bank.account_number ?? ''}\n口座名義: ${bank.account_holder ?? ''}`
  }
  return `\n\nPayment details:\nBank: ${bank.bank_name}\nBranch: ${bank.branch_name ?? ''}\nAccount type: ${bank.account_type ?? ''}\nAccount number: ${bank.account_number ?? ''}\nAccount holder: ${bank.account_holder ?? ''}`
}

export function getTemplate(offset: number, lang: 'ja' | 'en', input: TemplateInput): Template {
  const amountStr = formatAmount(input.amount, input.currency)
  const bank = bankSection(input.bankDetails, lang)

  if (lang === 'ja') {
    if (offset < 0) {
      return {
        subject: `【ご確認】請求書 ${input.invoiceNumber} のお支払期日について`,
        body: `${input.clientName} 様\n\nお世話になっております。${input.businessName}です。\n\n請求書 ${input.invoiceNumber}（${amountStr}）のお支払期日が ${input.dueDate} に迫っております。\nご確認のほど、よろしくお願いいたします。${bank}\n\n何卒よろしくお願いいたします。`,
      }
    }
    if (offset === 0) {
      return {
        subject: `本日締切：請求書 ${input.invoiceNumber} のお支払いについて`,
        body: `${input.clientName} 様\n\nお世話になっております。${input.businessName}です。\n\n請求書 ${input.invoiceNumber}（${amountStr}）の本日がお支払期日となっております。\nご確認いただけますと幸いです。${bank}\n\nよろしくお願いいたします。`,
      }
    }
    if (offset <= 7) {
      return {
        subject: `【お支払いのお願い】請求書 ${input.invoiceNumber}（期日超過）`,
        body: `${input.clientName} 様\n\nお世話になっております。${input.businessName}です。\n\n請求書 ${input.invoiceNumber}（${amountStr}、お支払期日：${input.dueDate}）につきまして、\nまだお振込みが確認できておりません。行き違いでしたら恐れ入りますが、\nご確認のほどよろしくお願いいたします。${bank}\n\nお忙しいところ恐れ入りますが、よろしくお願いいたします。`,
      }
    }
    return {
      subject: `【至急ご確認ください】請求書 ${input.invoiceNumber} のお支払いについて`,
      body: `${input.clientName} 様\n\nお世話になっております。${input.businessName}です。\n\n請求書 ${input.invoiceNumber}（${amountStr}、お支払期日：${input.dueDate}）につきまして、\nお支払期日を大幅に過ぎておりますが、まだご入金が確認できておりません。\nお手数をおかけいたしますが、至急ご確認いただけますでしょうか。${bank}\n\nご不明点等ございましたらお気軽にご連絡ください。`,
    }
  }

  if (offset < 0) {
    return {
      subject: `Heads up: Invoice ${input.invoiceNumber} is due soon`,
      body: `Hi ${input.clientName},\n\nJust a friendly heads-up that invoice ${input.invoiceNumber} (${amountStr}) is due on ${input.dueDate}.${bank}\n\nThanks,\n${input.businessName}`,
    }
  }
  if (offset === 0) {
    return {
      subject: `Invoice ${input.invoiceNumber} is due today`,
      body: `Hi ${input.clientName},\n\nInvoice ${input.invoiceNumber} (${amountStr}) is due today. Let me know if you have any questions.${bank}\n\nThanks,\n${input.businessName}`,
    }
  }
  if (offset <= 7) {
    return {
      subject: `Invoice ${input.invoiceNumber} is now overdue`,
      body: `Hi ${input.clientName},\n\nInvoice ${input.invoiceNumber} (${amountStr}), due ${input.dueDate}, appears to still be outstanding. If you've already sent payment, please disregard this — otherwise I'd appreciate it if you could take care of it when you get a chance.${bank}\n\nThanks,\n${input.businessName}`,
    }
  }
  return {
    subject: `Please review: Invoice ${input.invoiceNumber} — significantly overdue`,
    body: `Hi ${input.clientName},\n\nInvoice ${input.invoiceNumber} (${amountStr}), due ${input.dueDate}, is now well past due and I haven't been able to confirm payment. Could you look into this at your earliest convenience?${bank}\n\nPlease let me know if there's anything holding this up.\n\nThanks,\n${input.businessName}`,
  }
}
