// Default reminder copy, keyed by offset (days relative to due_date) and
// language. This is deliberately plain, hardcoded copy for now — Week 3
// adds an editable, AI-drafted version of these per user, stored in a new
// email_templates table. This week is about proving the pipeline fires
// correctly; the copy itself is the thing most worth having a native or
// fluent Japanese speaker review before it goes anywhere near a real client.
//
// One hard rule that should never change even once templates become
// AI-drafted: the amount, date, and invoice number are always inserted
// as plain variables here, never generated by a model. That's what makes
// it safe to automate.

type TemplateInput = {
  clientName: string
  invoiceNumber: string
  amount: number
  currency: string
  dueDate: string
  businessName: string
  bankDetails?: Record<string, string> | null
}

type Template = { subject: string; body: string }

function formatAmount(amount: number, currency: string) {
  return `${currency} ${amount.toLocaleString()}`
}

function bankSection(bankDetails: TemplateInput['bankDetails'], lang: 'ja' | 'en') {
  if (!bankDetails || Object.keys(bankDetails).length === 0) return ''
  const lines = Object.entries(bankDetails)
    .map(([k, v]) => `${k}: ${v}`)
    .join('\n')
  return lang === 'ja' ? `\n\nお振込先:\n${lines}` : `\n\nPayment details:\n${lines}`
}

export function getTemplate(offset: number, lang: 'ja' | 'en', input: TemplateInput): Template {
  const amountStr = formatAmount(input.amount, input.currency)
  const bank = bankSection(input.bankDetails, lang)

  if (lang === 'ja') {
    if (offset < 0) {
      return {
        subject: `【ご確認】請求書 ${input.invoiceNumber} のお支払期日について`,
        body: `${input.clientName} 様\n\nお世話になっております。${input.businessName}です。\n\n請求書 ${input.invoiceNumber}（${amountStr}）のお支払期日が ${input.dueDate} に迫っております。\nご確認のほど、よろしくお願いいたします。${bank}\n\n何卒よろしくお願いいたします。`,
      }
    }
    if (offset === 0) {
      return {
        subject: `本日締切：請求書 ${input.invoiceNumber} のお支払いについて`,
        body: `${input.clientName} 様\n\nお世話になっております。${input.businessName}です。\n\n請求書 ${input.invoiceNumber}（${amountStr}）の本日がお支払期日となっております。\nご確認いただけますと幸いです。${bank}\n\nよろしくお願いいたします。`,
      }
    }
    if (offset <= 7) {
      return {
        subject: `【お支払いのお願い】請求書 ${input.invoiceNumber}（期日超過）`,
        body: `${input.clientName} 様\n\nお世話になっております。${input.businessName}です。\n\n請求書 ${input.invoiceNumber}（${amountStr}、お支払期日：${input.dueDate}）につきまして、\nまだお振込みが確認できておりません。行き違いでしたら恐れ入りますが、\nご確認のほどよろしくお願いいたします。${bank}\n\nお忙しいところ恐れ入りますが、よろしくお願いいたします。`,
      }
    }
    return {
      subject: `【至急ご確認ください】請求書 ${input.invoiceNumber} のお支払いについて`,
      body: `${input.clientName} 様\n\nお世話になっております。${input.businessName}です。\n\n請求書 ${input.invoiceNumber}（${amountStr}、お支払期日：${input.dueDate}）につきまして、\nお支払期日を大幅に過ぎておりますが、まだご入金が確認できておりません。\nお手数をおかけいたしますが、至急ご確認いただけますでしょうか。${bank}\n\nご不明点等ございましたらお気軽にご連絡ください。`,
    }
  }

  if (offset < 0) {
    return {
      subject: `Heads up: Invoice ${input.invoiceNumber} is due soon`,
      body: `Hi ${input.clientName},\n\nJust a friendly heads-up that invoice ${input.invoiceNumber} (${amountStr}) is due on ${input.dueDate}.${bank}\n\nThanks,\n${input.businessName}`,
    }
  }
  if (offset === 0) {
    return {
      subject: `Invoice ${input.invoiceNumber} is due today`,
      body: `Hi ${input.clientName},\n\nInvoice ${input.invoiceNumber} (${amountStr}) is due today. Let me know if you have any questions.${bank}\n\nThanks,\n${input.businessName}`,
    }
  }
  if (offset <= 7) {
    return {
      subject: `Invoice ${input.invoiceNumber} is now overdue`,
      body: `Hi ${input.clientName},\n\nInvoice ${input.invoiceNumber} (${amountStr}), due ${input.dueDate}, appears to still be outstanding. If you've already sent payment, please disregard this — otherwise I'd appreciate it if you could take care of it when you get a chance.${bank}\n\nThanks,\n${input.businessName}`,
    }
  }
  return {
    subject: `Please review: Invoice ${input.invoiceNumber} — significantly overdue`,
    body: `Hi ${input.clientName},\n\nInvoice ${input.invoiceNumber} (${amountStr}), due ${input.dueDate}, is now well past due and I haven't been able to confirm payment. Could you look into this at your earliest convenience?${bank}\n\nPlease let me know if there's anything holding this up.\n\nThanks,\n${input.businessName}`,
  }
}
